version: '3.1'

services:
  #PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fonasa-app
    container_name: fonasa_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - fonasa

  #Nginx
  webserver:
    image: nginx:alpine
    container_name: fonasa_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "30019:80"
    volumes:
      - ./laravel:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - fonasa

  #MySQL
  db:
    image: mysql
    container_name: fonasa_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "33619:3306"
    environment:
      - "MYSQL_DATABASE=fonasa"
      - "MYSQL_USER=fonasa"
      - "MYSQL_PASSWORD=fonasa"
      - "MYSQL_ROOT_PASSWORD=secret"
      - "TZ=America/Santiago"
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - fonasa

  #MySQL adminer 
  adminer:
    image: adminer
    container_name: fonasa_adminer
    depends_on:
      - db
    restart: always
    ports:
      - 20019:8080
    networks:
      - fonasa

#Redes
networks:
  fonasa:
    driver: bridge
#Volumenes
volumes:
  dbdata:
    driver: local